#include <glib.h>
#include <IpcomEnums.h>

gint defaultTimeoutWFA 			= 500;	//ms
gint defaultTimeoutWFR 			= 500;	//ms
gfloat increaseTimerValueWFA		= 1.5;
gfloat increaseTimerValueWFR		= 2;
gint numberOfRetriesWFA			= 6;
gint numberOfRetriesWFR			= 2;

const gchar *OpContextStatusString[] = {
		"OPCONTEXT_STATUS_NONE",
		"OPCONTEXT_STATUS_REQUEST_SENT",
		"OPCONTEXT_STATUS_ACK_RECV",
		"OPCONTEXT_STATUS_PROCESS_RESPONSE",
		"OPCONTEXT_STATUS_PROCESS_REQUEST",
		"OPCONTEXT_STATUS_RESPONSE_SENT",
		"OPCONTEXT_STATUS_NOTIFICATION_SENT",
		"OPCONTEXT_STATUS_FINALIZE",
};

const gchar *OpContextTriggerString[] = {
		"OPCONTEXT_TRIGGER_SEND_REQUEST",		// 0
		"OPCONTEXT_TRIGGER_SEND_RESPONSE",
		"OPCONTEXT_TRIGGER_RECV_REQUEST",
		"OPCONTEXT_TRIGGER_RECV_RESPONSE",
		"OPCONTEXT_TRIGGER_RECV_ACK",
		"OPCONTEXT_TRIGGER_PROCESS_DONE",		// 5
		"OPCONTEXT_TRIGGER_SEND_NOTIFICATION",
		"OPCONTEXT_TRIGGER_WFA_EXPIRED",
		"OPCONTEXT_TRIGGER_WFR_EXPIRED",
		"OPCONTEXT_TRIGGER_FINALIZE",
};
